### ISSUE TITLE
Error in npm package

### ISSUE THREAD

**Issue by pmo1948** [audiojs/audio-through#2]
when using this as a dependency for audio-speaker, the following error appears:
```
C:\...\node_modules\audio-through\index.js:162
Through.prototype.writableObjectMode = true;
                                     ^

TypeError: Cannot set property writableObjectMode of #<Duplex> which has only a getter
    at Object.<anonymous> (C:\...\node_modules\audio-through\index.js:162:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\...\node_modules\audio-speaker\stream.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

node version 14.16.1

audio-through verision 2.2.3

The error did not appear with node v 12

**Comment by pmo1948** [comment]
I noticed after posting that it was for an older version. I will post the bug on the package that uses the older version instead of version 4
